<?php

namespace AppBundle\Repository;

/**
 * LivreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivreRepository extends \Doctrine\ORM\EntityRepository
{
    public function  recupLivresDispo() {

        $sql = "SELECT * FROM livre ";      

        $em = $this->getEntityManager();
        $connection = $em->getConnection();
        $statement = $connection->prepare($sql);
        $statement->execute();         

        return $statement->fetchAll();
    }

    public function  editLivresDispo($id) {

        $sql = "SELECT * FROM livre where id='".$id."'";  

        $em = $this->getEntityManager();
        $connection = $em->getConnection();
        $statement = $connection->prepare($sql);
        $statement->execute();        

        return $statement->fetchAll();
    }

    public function  reserverLivres($id,$idLivre) {
          
        $sql = "
        UPDATE Livre SET etat = 1,
        user_id=".$idLivre." where id=".$id ;                
          
        $em = $this->getEntityManager();
        $connection = $em->getConnection();
        $statement = $connection->prepare($sql);
        $statement->execute();        

         return $statement;
    }

    public function  getIdUser($pseudo) {

        $sql = "SELECT id FROM user where login='".$pseudo."'";              
          
        $em = $this->getEntityManager();
        $connection = $em->getConnection();
        $statement = $connection->prepare($sql);
        $statement->execute();              
        
        return $statement->fetchAll();
    }

    public function  mesEmprunt($user) {

        $sql = "SELECT * FROM livre where user_id=".$user;              
          
        $em = $this->getEntityManager();
        $connection = $em->getConnection();
        $statement = $connection->prepare($sql);
        $statement->execute();              
        
        return $statement->fetchAll();
    }

    public function  retourLivre($id) {
          
        $sql = "
        UPDATE Livre SET etat = 0,
        user_id= NULL where id=".$id ;                
          
        $em = $this->getEntityManager();
        $connection = $em->getConnection();
        $statement = $connection->prepare($sql);
        $statement->execute();        

         return $statement;
    }

    public function  donation($pseudo) {

        $sql = "SELECT * FROM livre where donation='".$pseudo."'";              
          
        $em = $this->getEntityManager();
        $connection = $em->getConnection();
        $statement = $connection->prepare($sql);
        $statement->execute();              
        
        return $statement->fetchAll();
    }
}
