<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function  connexion($login, $password) {


        $sql = "SELECT login,password
        FROM user
        WHERE EXISTS (
            SELECT login,password
            FROM user
            WHERE login='". $login."'and password= MD5('".$password."') )";        


        $em = $this->getEntityManager();
        $connection = $em->getConnection();
        $statement = $connection->prepare($sql);
        $statement->execute();
        

        $auth = ( $statement->fetchAll() != null) ? true : false;

        return $auth ; 
    }

    public function  getPhotoUser($pseudo) {


        $sql = "SELECT photo
        FROM user
        WHERE login='". $pseudo."'";        


        $em = $this->getEntityManager();
        $connection = $em->getConnection();
        $statement = $connection->prepare($sql);
        $statement->execute();
        

        return $statement->fetchAll();
    }
}
